export const MENTRAOS_MANAGER_PACKAGE_NAME = "com.mentra.mentra"
export const MENTRAOS_CORE_PACKAGE_NAME = "com.augmentos.augmentos_core"

export const MOCK_CONNECTION: boolean = false
export const INTENSE_LOGGING: boolean = false
export const ENABLE_PHONE_NOTIFICATIONS_DEFAULT: boolean = true

export const GET_APP_STORE_DATA_ENDPOINT = "/app_store_data"

export const SETTINGS_KEYS = {
  PREVIOUSLY_BONDED_PUCK: "PREVIOUSLY_BONDED_PUCK",
  ENABLE_PHONE_NOTIFICATIONS: "ENABLE_PHONE_NOTIFICATIONS",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
  SETTINGS_ACCESS_COUNT: "SETTINGS_ACCESS_COUNT",
  VISITED_LIVECAPTIONS_SETTINGS: "VISITED_LIVECAPTIONS_SETTINGS",
  CUSTOM_BACKEND_URL: "CUSTOM_BACKEND_URL",
  RECONNECT_ON_APP_FOREGROUND: "RECONNECT_ON_APP_FOREGROUND",
  HAS_EVER_ACTIVATED_APP: "HAS_EVER_ACTIVATED_APP",
  THEME_PREFERENCE: "THEME_PREFERENCE",
  DEV_MODE: "DEV_MODE",
  NEW_UI: "NEW_UI",
}
