/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mentraos_ble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mentraos_ble_PhoneToGlasses, mentraos_ble_PhoneToGlasses, AUTO)


PB_BIND(mentraos_ble_GlassesToPhone, mentraos_ble_GlassesToPhone, AUTO)


PB_BIND(mentraos_ble_DisconnectRequest, mentraos_ble_DisconnectRequest, AUTO)


PB_BIND(mentraos_ble_BatteryStateRequest, mentraos_ble_BatteryStateRequest, AUTO)


PB_BIND(mentraos_ble_BatteryStatus, mentraos_ble_BatteryStatus, AUTO)


PB_BIND(mentraos_ble_ChargingState, mentraos_ble_ChargingState, AUTO)


PB_BIND(mentraos_ble_GlassesInfoRequest, mentraos_ble_GlassesInfoRequest, AUTO)


PB_BIND(mentraos_ble_DeviceInfo, mentraos_ble_DeviceInfo, AUTO)


PB_BIND(mentraos_ble_DeviceFeatures, mentraos_ble_DeviceFeatures, AUTO)


PB_BIND(mentraos_ble_PairingModeRequest, mentraos_ble_PairingModeRequest, AUTO)


PB_BIND(mentraos_ble_HeadPositionRequest, mentraos_ble_HeadPositionRequest, AUTO)


PB_BIND(mentraos_ble_HeadPosition, mentraos_ble_HeadPosition, AUTO)


PB_BIND(mentraos_ble_HeadUpAngleConfig, mentraos_ble_HeadUpAngleConfig, AUTO)


PB_BIND(mentraos_ble_HeadUpAngleResponse, mentraos_ble_HeadUpAngleResponse, AUTO)


PB_BIND(mentraos_ble_PingRequest, mentraos_ble_PingRequest, AUTO)


PB_BIND(mentraos_ble_PongResponse, mentraos_ble_PongResponse, AUTO)


PB_BIND(mentraos_ble_MicStateConfig, mentraos_ble_MicStateConfig, AUTO)


PB_BIND(mentraos_ble_VadEnabledConfig, mentraos_ble_VadEnabledConfig, AUTO)


PB_BIND(mentraos_ble_VadConfig, mentraos_ble_VadConfig, AUTO)


PB_BIND(mentraos_ble_VadEvent, mentraos_ble_VadEvent, AUTO)


PB_BIND(mentraos_ble_DisplayText, mentraos_ble_DisplayText, AUTO)


PB_BIND(mentraos_ble_DisplayImage, mentraos_ble_DisplayImage, AUTO)


PB_BIND(mentraos_ble_PreloadImage, mentraos_ble_PreloadImage, AUTO)


PB_BIND(mentraos_ble_DisplayCachedImage, mentraos_ble_DisplayCachedImage, AUTO)


PB_BIND(mentraos_ble_ClearCachedImage, mentraos_ble_ClearCachedImage, AUTO)


PB_BIND(mentraos_ble_DisplayScrollingText, mentraos_ble_DisplayScrollingText, AUTO)


PB_BIND(mentraos_ble_DisplayPowerConfig, mentraos_ble_DisplayPowerConfig, AUTO)


PB_BIND(mentraos_ble_BrightnessConfig, mentraos_ble_BrightnessConfig, AUTO)


PB_BIND(mentraos_ble_AutoBrightnessConfig, mentraos_ble_AutoBrightnessConfig, AUTO)


PB_BIND(mentraos_ble_AutoBrightnessMultiplier, mentraos_ble_AutoBrightnessMultiplier, AUTO)


PB_BIND(mentraos_ble_DrawLine, mentraos_ble_DrawLine, AUTO)


PB_BIND(mentraos_ble_DrawRect, mentraos_ble_DrawRect, AUTO)


PB_BIND(mentraos_ble_DrawCircle, mentraos_ble_DrawCircle, AUTO)


PB_BIND(mentraos_ble_CommitDisplay, mentraos_ble_CommitDisplay, AUTO)


PB_BIND(mentraos_ble_DisplayDistanceConfig, mentraos_ble_DisplayDistanceConfig, AUTO)


PB_BIND(mentraos_ble_DisplayHeightConfig, mentraos_ble_DisplayHeightConfig, AUTO)


PB_BIND(mentraos_ble_ImageTransferComplete, mentraos_ble_ImageTransferComplete, AUTO)


PB_BIND(mentraos_ble_ImuEnabledConfig, mentraos_ble_ImuEnabledConfig, AUTO)


PB_BIND(mentraos_ble_ImuSingleRequest, mentraos_ble_ImuSingleRequest, AUTO)


PB_BIND(mentraos_ble_ImuStreamConfig, mentraos_ble_ImuStreamConfig, AUTO)


PB_BIND(mentraos_ble_ImuData, mentraos_ble_ImuData, AUTO)


PB_BIND(mentraos_ble_Vector3, mentraos_ble_Vector3, AUTO)


PB_BIND(mentraos_ble_ButtonEvent, mentraos_ble_ButtonEvent, AUTO)


PB_BIND(mentraos_ble_HeadGesture, mentraos_ble_HeadGesture, AUTO)


PB_BIND(mentraos_ble_HeadGestureConfig, mentraos_ble_HeadGestureConfig, AUTO)


PB_BIND(mentraos_ble_RestartRequest, mentraos_ble_RestartRequest, AUTO)


PB_BIND(mentraos_ble_FactoryResetRequest, mentraos_ble_FactoryResetRequest, AUTO)

















